name: syntonic_components
description: The plugin that core package for your projects.
version: 1.0.0
homepage:

environment:
  sdk: ^3.6.0

dependencies:
#  arb_merger:
#    path: ../arb_merger
  async: ^2.8.2
  build_runner: ^2.3.2
#  copy_with_extension_gen: ^5.0.4
  cupertino_icons: ^1.0.2
#  date_format: ^2.0.2
  cloud_firestore: ^5.6.8

  device_info_plus: ^9.0.2
#  drift: ^2.2.0
  dynamic_color: ^1.6.7
#  equatable: ^2.0.5
  extension_google_sign_in_as_googleapis_auth: ^2.0.10
  file_picker: ^8.1.2
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_database: ^11.3.6
  firebase_storage: ^12.4.6
  flutter:
    sdk: flutter
#  flutter_device_type: ^0.4.0
#  flutter_facebook_auth: ^4.4.1+1
#  flutter_hooks: ^0.18.0
  flutter_launcher_icons: ^0.13.1
#  flutter_line_liff: ^0.0.3
#  flutter_line_sdk: ^2.3.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.1
#  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.3
  freezed_annotation: ^2.4.1
#  get: ^4.1.4
  google_fonts: 6.1.0
  google_mobile_ads: ^6.0.0
  google_sign_in: ^6.3.0
  google_sign_in_ios: ^5.8.1
  googleapis: ^11.3.0
  html: ^0.15.4
  http: ^1.0.0
  image_picker: ^1.0.7
  intl: ^0.20.2
#  intl_phone_number_input: ^0.7.0+2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
#  linked_scroll_controller: ^0.2.0
  material_color_utilities: ^0.11.1
  palette_generator: ^0.3.3+3
  path: ^1.8.0
  path_provider: ^2.0.11
  package_info_plus: ^4.0.2
  percent_indicator: ^4.2.3
#  phone_number: ^1.0.0
  provider: ^6.0.3
  rate_my_app: ^2.0.0
  scrollable_positioned_list: ^0.3.2
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^7.0.1
  sliver_tools: ^0.2.12
  skeletonizer: ^2.1.0+1
  sqflite: ^2.4.2
  sqlite3_flutter_libs: ^0.5.10
#  tuple: ^2.0.0
  url_launcher: ^6.0.10
  uuid: ^3.0.7
  version: ^3.0.2
  visibility_detector: ^0.3.3
  vs_scrollbar: ^1.0.0
#  web_browser_detect: ^2.0.2
dev_dependencies:
  drift_dev: ^2.2.0+1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.4.6
#  freezed_annotation: ^2.4.1
#  json_annotation: ^4.8.1
  source_gen: ^1.2.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dev.soosuuk.syntonic_components
        pluginClass: SyntonicComponentsPlugin
      ios:
        pluginClass: SyntonicComponentsPlugin

  uses-material-design: true

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: swiss721
      fonts:
        - asset: assets/fonts/Swiss721BT-Medium.ttf
          weight: 500

  generate: true

arb_merger:
  supported_locales: ["ja", "en"]
  input_filepath: "assets/l10n"
  output_filepath: "assets/l10n"
